name: Compile and attach to Github release DRAFT
# The action must be manually triggered and provided with the version number
# It will create a new draft release with the provided version as a tag
# The version will be used in gradle.properties to build the mod JAR and resourcepack ZIP
# The created artifacts will be attached to the release draft
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (X.Y.Z format, e.g. 1.0.0)'
        required: true
        type: string

# permissions required to write to the github release
permissions:
  contents: write

env:
  # COMMON PARAMETERS
  JAVA_VERSION: 21
  GAME_VERSIONS: |
    [1.21.1]
  GAME_VERSION_FILTER: releases
  VERSION_TYPE: release
  MOD_ID: stellaris_stellarview_compatibility

  # MOD VARIANT
  MOD_LOADER: neoforge
  MOD_PRIMARY_FILE_GLOB: stellaris_stellarview_compatibility-*.jar

  # RESOURCEPACK VARIANT
  RESOURCEPACK_PRIMARY_FILE_GLOB: stellaris_stellarview_compatibility-*.zip

jobs:
  version:
    name: Resolves the version from the release tag
    runs-on: ubuntu-slim
    outputs:
      # the version will be available as ${{ needs.version.outputs.version }} in dependent jobs
      # Clean version X.Y.Z
      version: ${{ steps.extract_version.outputs.VERSION }}
      # Tag name vX.Y.Z
      tag: v${{ steps.extract_version.outputs.VERSION }}
    steps:
      # id required to reference the output value
      - id: extract_version
        name: Format Version
        run: |
          VERSION="${{ inputs.version }}"
          if [[ "$VERSION" == v* ]]; then
            VERSION=${VERSION:1}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

  build-resourcepack:
    name: Build Resource Pack ZIP artifact
    runs-on: ubuntu-latest
    needs: [version]
    env:
      DIRECTORY: src/main/templates/resourcepack
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Prepare Resource Pack files
        run: |
          mv src/main/templates/assets ${{ env.DIRECTORY }}/assets

      - name: Append version to pack.mcmeta
        run: |
          cd ${{ env.DIRECTORY }}
          jq --arg version "${{ needs.version.outputs.version }}" '.pack.description += " Version: v" + $version' pack.mcmeta > pack.mcmeta.tmp
          mv pack.mcmeta.tmp pack.mcmeta

      - name: Create Resource Pack ZIP
        run: |
          cd ${{ env.DIRECTORY }}
          zip -r ${{ env.MOD_ID }}-${{ needs.version.outputs.tag }}-resourcepack.zip .

      - name: Upload Resource Pack Artifact
        uses: actions/upload-artifact@v6
        with:
          name: resourcepack-artifact
          path: ${{ env.DIRECTORY }}/${{ env.RESOURCEPACK_PRIMARY_FILE_GLOB }}
          if-no-files-found: error

  build-jar:
    name: Build mod JAR artifact
    runs-on: ubuntu-slim
    needs: [version]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - name: Set execution permissions for Gradle wrapper
        run: chmod +x gradlew

      - name: Set version in gradle.properties
        # replaces the mod_version property in gradle.properties with the extracted TAG version
        run: |
          sed -i "s/^mod_version=.*/mod_version=${{ needs.version.outputs.version }}-${{ env.MOD_LOADER }}/" gradle.properties

      - name: Build Mod JAR
        run: ./gradlew build

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v6
        with:
          name: mod-jar-artifact
          path: build/libs/${{ env.MOD_PRIMARY_FILE_GLOB }}
          if-no-files-found: error

  create-release:
    name: Create Draft Release and Attach Artifacts
    runs-on: ubuntu-slim
    needs: [version, build-resourcepack, build-jar]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-artifacts
          # Merges downloaded artifacts into the target path directly instead of creating subfolders per artifact name
          merge-multiple: true

      - name: Create Release Draft
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.version.outputs.tag }}
          name: ${{ needs.version.outputs.tag }}
          draft: true
          # attach all files from the directory
          files: release-artifacts/*